### ISSUE TITLE
properties of undefined: checkPathInterval, __packedPos

### ISSUE THREAD

**Issue by joshuacox** [TooAngel/screeps#558] opened 2019-11-01 15:43 UTC
I get bunch of weird errors after deploying:

```
Cannot read property 'checkPathInterval' of undefined TypeError: Cannot read property 'checkPathInterval' of undefined
```

```
Cannot read property '__packedPos' of undefined TypeError: Cannot read property '__packedPos' of undefined
```

```
TypeError: fillerPos.findNearPosition is not a function TypeError: fillerPos.findNearPosition is not a function
```

Any clue what I might have done wrong?

**Comment by TooAngel** [comment] 2019-11-15 09:34
Not yet sure what the issue is, how are you trying to use it as bot or as your own code?

 `__packedPos` is not part of the repository, so not sure.

For the others, do you have a full stack trace?

**Comment by locomute** [comment] 2019-11-19 00:31
I get the same error with the "_packedPos"

**Comment by TooAngel** [comment] 2019-11-19 10:54
I think the error comes up when the code tries to create a `RoomPosition` which is outside of the map. I could catch now certain cases. When the PR gets merged it should be fixed.

**Comment by joshuacox** [comment] 2019-11-19 21:34
Seems to be an issue with the engine:
```
node_modules/@screeps/engine/dist/game/rooms.js:        Object.defineProperty(this, '__packedPos', {
node_modules/@screeps/engine/dist/game/rooms.js:                return this.__packedPos >> 8 & 0xff;
node_modules/@screeps/engine/dist/game/rooms.js:                this.__packedPos = this.__packedPos & ~(0xff << 8) | val << 8;
node_modules/@screeps/engine/dist/game/rooms.js:                return this.__packedPos & 0xff;
node_modules/@screeps/engine/dist/game/rooms.js:                this.__packedPos = this.__packedPos & ~0xff | val;
node_modules/@screeps/engine/dist/game/rooms.js:                var roomName = roomNames[this.__packedPos >>> 16];
node_modules/@screeps/engine/dist/game/rooms.js:                    return utils.getRoomNameFromXY((this.__packedPos >>> 24) - kMaxWorldSize2, (this.__packedPos >>> 16 & 0xff) - kMaxWorldSize2);
node_modules/@screeps/engine/dist/game/rooms.js:                this.__packedPos = this.__packedPos & ~(0xffff << 16) | xy[0] << 24 | xy[1] << 16;
node_modules/@screeps/engine/dist/game/rooms.js:        if (firstArg.__packedPos !== undefined) {
node_modules/@screeps/engine/dist/game/rooms.js:            return firstArg.__packedPos === this.__packedPos;
node_modules/@screeps/engine/src/game/rooms.js:        Object.defineProperty(this, '__packedPos', {
node_modules/@screeps/engine/src/game/rooms.js:                return (this.__packedPos >> 8) & 0xff;
node_modules/@screeps/engine/src/game/rooms.js:                this.__packedPos = this.__packedPos & ~(0xff << 8) | val << 8;
node_modules/@screeps/engine/src/game/rooms.js:                return this.__packedPos & 0xff;
node_modules/@screeps/engine/src/game/rooms.js:                this.__packedPos = this.__packedPos & ~0xff | val;
node_modules/@screeps/engine/src/game/rooms.js:                let roomName = roomNames[this.__packedPos >>> 16];
node_modules/@screeps/engine/src/game/rooms.js:                        (this.__packedPos >>> 24) - kMaxWorldSize2,
node_modules/@screeps/engine/src/game/rooms.js:                        (this.__packedPos >>> 16 & 0xff) - kMaxWorldSize2
node_modules/@screeps/engine/src/game/rooms.js:                this.__packedPos = this.__packedPos & ~(0xffff << 16) | xy[0] << 24 | xy[1] << 16;
node_modules/@screeps/engine/src/game/rooms.js:        if (firstArg.__packedPos !== undefined) {
node_modules/@screeps/engine/src/game/rooms.js:            return firstArg.__packedPos === this.__packedPos;
node_modules/@screeps/driver/build/runtime.bundle.js:        Object.defineProperty(this, '__packedPos', {
node_modules/@screeps/driver/build/runtime.bundle.js:                return (this.__packedPos >> 8) & 0xff;
node_modules/@screeps/driver/build/runtime.bundle.js:                this.__packedPos = this.__packedPos & ~(0xff << 8) | val << 8;
node_modules/@screeps/driver/build/runtime.bundle.js:                return this.__packedPos & 0xff;
node_modules/@screeps/driver/build/runtime.bundle.js:                this.__packedPos = this.__packedPos & ~0xff | val;
node_modules/@screeps/driver/build/runtime.bundle.js:                let roomName = roomNames[this.__packedPos >>> 16];
node_modules/@screeps/driver/build/runtime.bundle.js:                        (this.__packedPos >>> 24) - kMaxWorldSize2,
node_modules/@screeps/driver/build/runtime.bundle.js:                        (this.__packedPos >>> 16 & 0xff) - kMaxWorldSize2
node_modules/@screeps/driver/build/runtime.bundle.js:                this.__packedPos = this.__packedPos & ~(0xffff << 16) | xy[0] << 24 | xy[1] << 16;
node_modules/@screeps/driver/build/runtime.bundle.js:        if (firstArg.__packedPos !== undefined) {
node_modules/@screeps/driver/build/runtime.bundle.js:            return firstArg.__packedPos === this.__packedPos;
Binary file node_modules/@screeps/driver/build/runtime.snapshot.bin matches
```

**Comment by joshuacox** [comment] 2019-11-19 21:35
@TooAngel which PR?  I can test

**Comment by TooAngel** [comment] 2019-11-20 07:27
https://github.com/TooAngel/screeps/pull/560

**Comment by joshuacox** [comment] 2019-11-20 07:42
uploading now and testing

**Closed** 2019-11-24 20:51 UTC

**Comment by joshuacox** [comment] 2019-11-25 07:07
just wanted to report back that I reached global control level 2
