### ISSUE TITLE
Excessive carry spawns

### ISSUE THREAD

**Issue by DarkDestry** [TooAngel/screeps#464] opened 2017-10-07 13:40 UTC
Hi, i just got into trying the bot and on my first attempt trying I have the issue of excessive carrys spawning. This resulted in a deadlock as they form a long chain blocking the path.

![image](https://user-images.githubusercontent.com/3728955/31308336-e93594a6-aba7-11e7-93b8-34546dba2861.png)

It is worth noting that the carrys are not picking up the dropped resources either. The most extreme left 2 carry is swapping position with each other constantly.

**Comment by TooAngel** [comment] 2017-10-12 21:49
Thx for reporting. We had some carries issues in the last month. I fix was released recently, can you check if the master branch has the error, too?

**Comment by DarkDestry** [comment] 2017-10-14 18:12
I have respawned else where so I don't think I can test it.if anyone knows how to replicate a room layout to test it it's E52S32 on shard 1. The spawn location is 32,27

**Comment by TooAngel** [comment] 2019-11-27 18:51
Well, I guess the issue is not existent in that form anymore, the linked PR will close the issue.

**Closed** 2019-12-03 16:15 UTC
