### ISSUE TITLE
Sourcer and Carry Creep Role Failed

### ISSUE THREAD

**Issue by aceofaces** [TooAngel/screeps#84] opened 2017-01-04 09:55 UTC
Regression occurred sometime recently.  A single room works fine, but once external rooms need sourcers and carry they freeze in position once on the main path.

Clearing creep memory does nothing to resolve, clearing the main rooms memory does resolve the issue for a period of time.

Stack traces:
http://pastebin.com/hSagsb3G
http://pastebin.com/iRHvrnmL

**Comment by aceofaces** [comment] 2017-01-05 18:23
This issue occurs when manually sending a reserver to a neighboring room when the main room has a misplaced spawn.  Once the misplaced spawn is resolved the issue no longer occurs. 
I rolled back to 1.1.12 and the issue was still happening.  My misplaced spawn is fixed now so I can't test further.

**Comment by TooAngel** [comment] 2017-01-05 21:47
Could see the error on the first looks, quickly copying the important line here:

```
16502814 W6S77  sourcer-310          [room W6S77 pos 28,23] Executing creep role failed: W6S77 sourcer-310 586c4a5b01d50d92200cc243 {"x":28,"y":23,"roomName":"W6S77"} TypeError: Cannot read property 'x' of undefined
TypeError: Cannot read property 'x' of undefined
    at Object.roles.sourcer.preMove (role_sourcer:35:24)
```

Can be tested and fixed on a private server.

**Closed** 2017-01-06 21:31 UTC

**Comment by TooAngel** [comment] 2017-01-06 21:32
You can add "#Fixes 84" to the commit message and if that commit gets merged, the issue is automatically closed.
