### ISSUE TITLE
CPU conservation

### ISSUE THREAD

**Issue by Evanito** [TooAngel/screeps#16] opened 2016-12-10 07:25 UTC
The bot is very greedy when it comes to CPU usage, which is a huge issue for newer players with only 30 CPU. It will simply run itself dry and then spam my emails with "no CPU in bucket" errors. I would recommend the usage of a "defer" module which contains greedy commands that don't necessarily need to be run every tick and are deferred until the user has a decent amount of CPU in the bucket.

In addition, as an ad-hoc solution I added a simple command to the very beginning of main.js that would cancel running on that tick if the bucket is empty. The tickLimit is multiplied by two because that is usually how much CPU it uses for me, but it only needs to be how much the script is expected to run on that tick.
```
  if (Game.cpu.bucket < Game.cpu.tickLimit * 2) {
  return;
  }
```

I also noticed you have support for a profiler, but do not include the screeps-profiler.js (https://github.com/gdborton/screeps-profiler/blob/master/screeps-profiler.js) when it has no license and thus defaults to "open." No one will give you trouble for including it in your repository. (You could even potentially use a git submodule)

Even with support for it, I don't see that it even does anything for the user, as the bot doesn't seem to do anything with the data it provides.

The config option `serializePath`, which would seem to improve CPU performance, is broken with the error:
```
Executing room failed: W15N69 TypeError: string.split is not a function TypeError: string.split is not a function
    at Function.Room.stringToPath (config_room_utils:63:22)
    at Room.checkPath (config_room_basebuilder:149:19)
    at wrappedFunction [as checkPath] (screeps-profiler:96:29)
    at Room.buildBase (config_room_controller:25:14)
    at wrappedFunction [as buildBase] (screeps-profiler:96:29)
    at Room.executeRoom (config_room_my:210:8)
    at wrappedFunction [as executeRoom] (screeps-profiler:96:29)
    at Room.myHandleRoom (config_room_my:49:15)
    at wrappedFunction [as myHandleRoom] (screeps-profiler:96:29)
    at Room.handle (config_room:16:17)
```
and so does not help.

**Comment by TooAngel** [comment] 2016-12-10 12:57
Thank you for looking into this, I really appreciate it.

To give you some background, I'm aware of CPU issues (I guess this is a usual problem of the game). On the live server I'm currently GCL 22 so I have a lot more CPU, but I still sometimes run into the CPU issue. Currently I'm mostly working on the private server where you have 100 CPU from the start. My current goal is to have the private server bot stable and if I find time I look into improving on the CPU. I'm usually open a PR as soon as I have some improvements, looking into or using this if you have issues, is often a good idea.

I think your skipping a tick suggestion is a `dirty hack`, but it can help for now, would just be one more 'dirty hack' :-)  Pull Request welcome, maybe with a friendly message like: 'TooAngel, fix your CPU issues, quickly, you lazy ...'.

The screeps-profiler is included in the `package.json` https://github.com/TooAngel/screeps/blob/master/package.json#L21 I think it is currently not copied to the dist directory. You could add an additional grunt task, which copies the `screeps-profiler.js` from the `node_modules` directory. I guess I will do that, too, next time I'm working on screeps. I would prefer not to include the library directly. If it is available it can be enabled in the `config.js` https://github.com/TooAngel/screeps/blob/master/src/config.js#L7 How to use it is written here: https://github.com/gdborton/screeps-profiler#console-api You can get the profiled data via the console and don't have to change or include it in your code.

The `serializePath` config option stores the precalculated paths in a compress format in Memory. The idea behind it is to save memory with the costs of CPU, so shouldn't help you with the CPU issues, but you can try. You can enable it, but you have to delete the rooms in Memory `delete Memory.rooms` in the console, the Memory will build up by itself. The exception is thrown, because the path is not in the expected format, after changing the config.

Last but not least, I like you suggestion with executing long running tasks only if the CPU bucket is full, thought about it, too. Didn't start to implement it yet. Another approach I took, e.g. to check the room structures (build new and destroy wrong) is working with a counter which increases if nothing is to do. And based on this counter the decision is done when to execute it next. (So in the begin very often, later it will be rarely executed) E.g. https://github.com/TooAngel/screeps/blob/master/src/config_room_controller.js#L35

I hope I addressed all your suggestions, otherwise let me know.
If you have any kind of improvement (I'm pretty sure every part of the code can be improved), PRs are welcome.

Have fun with the TooAngel AI.

**Comment by mschultheiss83** [comment] 2017-01-04 20:52
i think cacheing those filter functions like in #36  would improve a lot the CPU conservation

**Comment by WhiteHalmos** [comment] 2017-01-04 23:13
Aren't filters cached by default? Or do you mean caching the result?

**Comment by mschultheiss83** [comment] 2017-01-04 23:40
> Aren't filters cached by default?
i dont know, but both, if not maybe with an optional Game.ticks param
like filter for role, queue, hostile, player name, and so
the more complex a filter the lesser it will be used, i think,

**Comment by TooAngel** [comment] 2017-01-04 23:59
@Evanito I think the issues are addressed by the commits. The CPU issue is IMHO a screeps inherent challenge and it has improved in the last time. Do you think the issue is still valid?

**Comment by Evanito** [comment] 2017-01-05 00:34
@TooAngel Yes, but I still beleive CPU management should be an integral part of the bot. I was just downgraded to 10CPU and have no intention to resubscribe (Not in the budget) and my script is only able to support a single harvester that can barely maintain the controller from downgrading, much less ever be able to upgrade it. https://screeps.com/a/#!/room/E78N37

**Comment by TooAngel** [comment] 2017-08-19 22:48
With the last month a lot has improved, most of the topics are addressed. Currently the 10 CPU is not issue. Will close this one.

**Closed by TooAngel** 2017-08-19 22:48 UTC
